compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  # fixing https://github.com/vercel/next.js/issues/38939
  eslint-config-next@*:
    dependencies:
      next: "*"
  # the following changes are necessary because tsc was loading
  # the wrong version of @types/react (it was taking 18 from main
  # instead of 19 from the web package) & linting was failing
  # START FIX FOR TSC
  "@cowprotocol/widget-react@*":
    peerDependencies:
      react: "^19.0.0"
      "@types/react": "^19.0.0"
  react-papaparse@*:
    peerDependencies:
      react: "^19.0.0"
  "@storybook/core@*":
    dependencies:
      react: "^19.0.0"
      "@types/react": "^19.0.0"
  # END FIX FOR TSC

npmPublishRegistry: "https://registry.npmjs.org"
npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  os: [darwin, linux]
  cpu: [x64, arm64]

npmScopes:
  safe-global:
    npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
